set nocompatible

syntax on

set hidden

set wildmenu

set showcmd

set hlsearch
set incsearch

set ignorecase
set smartcase

set backspace=indent,eol,start

set autoindent

set ruler

set laststatus=2

set confirm

set visualbell

set number

set notimeout ttimeout ttimeoutlen=200

set history=1000

set title

set pastetoggle=<F2>

set listchars=tab:>-,trail:·,eol:$
nmap <silent> <leader>sp :set nolist!<CR>

set shiftwidth=2
set shiftround
set softtabstop=4
set expandtab
